name: hagelslag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - s3fs
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - scikit-learn
  - pytest
  - h5py
  - pip
  - pyproj
  - pygrib
  - scikit-image
  - jupyter
  - jupyterlab
  - arrow
  - cython
  - sphinx
  - mock
  - jasper
  - flake8
  - zarr
  - pyarrow
  - pip:
      - .
